export const data = {
    products: [
        {
            id: 1,
            name: "iPhone 12 Pro Max 128GB",
            price: 31990000,
            salePrice: 30000000,
            type: "iphone",
            image: "https://cdn.tgdd.vn/Products/Images/42/213033/iphone-12-pro-max-xanh-duong-new-600x600-600x600.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 2,
            name: "iPhone XR 128GB",
            price: 12990000,
            salePrice: 11000000,
            type: "iphone",
            image: "https://cdn.tgdd.vn/Products/Images/42/191483/iphone-xr-128gb-600x600.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 3,
            name: "Samsung Galaxy S21 Ultra 5G 128GB",
            price: 30990000,
            salePrice: 29000000,
            type: "samsung",
            image: "https://cdn.tgdd.vn/Products/Images/42/226316/samsung-galaxy-s21-ultra-bac-600x600-1-600x600.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 4,
            name: "Samsung Galaxy Note 10+",
            price: 16990000,
            salePrice: 15000000,
            type: "samsung",
            image: "https://cdn.tgdd.vn/Products/Images/42/206176/samsung-galaxy-note-10-plus-silver-new-600x600.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 5,
            name: "OPPO Reno5",
            price: 8990000,
            salePrice: 8000000,
            type: "oppo",
            image: "https://cdn.tgdd.vn/Products/Images/42/220438/oppo-reno5-trang-600x600-1-600x600.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 6,
            name: "OPPO A15",
            price: 3990000,
            salePrice: 3000000,
            type: "oppo",
            image: "https://cdn.tgdd.vn/Products/Images/42/229885/oppo-a15-black-600x600-2-600x600.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 7,
            name: "Vivo Y51",
            price: 5590000,
            salePrice: 5300000,
            type: "vivo",
            images: "https://cdn2.cellphones.com.vn/358x/media/catalog/product/v/i/vivo-y15a-trang-xanh-600x600_1.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 8,
            name: "Vivo V20",
            price: 7790000,
            salePrice: 7780000,
            type: "vivo",
            image: "https://cdn.tgdd.vn/Products/Images/42/232614/vivov202021den-600x600.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 9,
            name: "Xiaomi Redmi Note 10 (6GB/128GB)",
            price: 4690000,
            salePrice: 4680000,
            type: "xiaomi",
            image: "https://cdn.tgdd.vn/Products/Images/42/222758/xiaomi-redmi-note-10-thumb-green-600x600-1-600x600.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 10,
            name: "Xiaomi Mi 11 5G",
            price: 21990000,
            salePrice: 21880000,
            type: "xiaomi",
            image: "https://cdn.tgdd.vn/Products/Images/42/226264/xiaomi-mi-11-xanhduong-600x600-600x600.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 11,
            name: "Realme 7 Pro",
            price: 8490000,
            salePrice: 8000000,
            type: "realme",
            image: "https://cdn.tgdd.vn/Products/Images/42/227689/realme-7-pro-bac-600x600.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 12,
            name: "Realme C3 (3GB/32GB)",
            price: 2790000,
            salePrice: 2790000,
            type: "realme",
            image: "https://cdn.tgdd.vn/Products/Images/42/218361/realme-c3-do-600x600-1-600x600.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 13,
            name: "Vsmart Aris Pro",
            price: 7490000,
            salePrice: 7000000,
            type: "vsmart",
            image: "https://cdn.tgdd.vn/Products/Images/42/228531/vsmart-aris-pro-green-600jpg-600x600.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 14,
            name: "Vsmart Star 4 (3GB/32GB)",
            price: 2290000,
            salePrice: 2000000,
            type: "vsmart",
            image: "https://cdn.tgdd.vn/Products/Images/42/225158/vsmart-start-3gb-den-600x600.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 15,
            name: "Samsung Galaxy A52 5G",
            price: 2590000,
            salePrice: 2000000,
            type: "samsung",
            image: "https://cdn.tgdd.vn/Products/Images/42/235440/samsung-galaxy-a52-5g-thumb-black-600x600-600x600.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 16,
            name: "iPhone SE 64GB ",
            price: 11490000,
            salePrice: 11000000,
            type: "iphone",
            image: "https://cdn.tgdd.vn/Products/Images/42/230410/iphone-se-2020-trang-600x600-600x600.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 17,
            name: "iPhone 12 256GB",
            price: 25490000,
            salePrice: 23000000,
            type: "iphone",
            image: "https://cdn.tgdd.vn/Products/Images/42/230410/iphone-se-2020-trang-600x600-600x600.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 18,
            name: "iPhone 12 mini 128GB",
            price: 17490000,
            salePrice: 15000000,
            type: "iphone",
            image: "https://cdn.tgdd.vn/Products/Images/42/228741/iphone-mini-do-new-600x600-600x600.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 19,
            name: "Samsung Galaxy A32",
            price: 6490000,
            salePrice: 6000000,
            type: "samsung",
            image: "https://cdn.tgdd.vn/Products/Images/42/234315/samsung-galaxy-a32-4g-thumb-tim-600x600-600x600.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 20,
            name: "Samsung Galaxy M51",
            price: 8990000,
            salePrice: 8000000,
            type: "samsung",
            image: "https://cdn.tgdd.vn/Products/Images/42/217536/samsung-galaxy-m51-trang-new-600x600-600x600.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 21,
            name: "Xiaomi Redmi Note 10 (6GB/128GB)",
            price: 5000000,
            salePrice: 5000000,
            type: "xiaomi",
            image: "https://cdn.tgdd.vn/Products/Images/42/222758/xiaomi-redmi-note-10-thumb-green-600x600.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 22,
            name: "Xiaomi Mi 11 Lite",
            price: 7900000,
            salePrice: 7000000,
            type: "xiaomi",
            image: "https://cdn.tgdd.vn/Products/Images/42/233241/xiaomi-mi-11-lite-4g-blue-600x600.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 23,
            name: "Xiaomi Redmi Note 9S",
            price: 5600000,
            salePrice: 5000000,
            type: "xiaomi",
            image: "https://cdn.tgdd.vn/Products/Images/42/214924/xiaomi-redmi-note-9s-xanh-new-600x600-600x600.jpg",
            rating: 5,
            numReviews: 1,
            reviews: [
                {
                    name: "cao kha hieu",
                    star: 5,
                    comment: "ngon",
                },
            ],
        },
        {
            id: 24,
            name: "iPhone 11 64GB I Chính hãng VN/A",
            price: 18000000,
            salePrice: 10790000,
            amount: 100,
            type: "iphone",
            image: "https://cdn2.cellphones.com.vn/358x/media/catalog/product/i/p/iphone_11_white_4_.png",
            cloudinary_id: "",
            rating: 0,
            os: "ios",
            ram: "4GB",
            battery: "3110mAh",
            rom: "128GB",
            camera: "12MP",
            special:
                "Cụm camera phía sau đã được sắp xếp lại giống với Huawei Mate 20 Pro. Màn hình điện thoại iPhone 11 sở hữu notch rộng dài như các phiên bản tiền nhiệm và giữ nguyên thiết kế như iPhone XR. Notch tích hợp Face ID, loa âm thanh và camera selfie.",
            design: "Độ trễ màn hình gần như bằng 0, tốc độ làm mới màn hình nằm ở mức 60 Hz. Độ chính xác màu đạt đến mức tối đa, điểm DeltaE trung bình đạt 1.1, độ lệch tối đa 2.4 RGB. Ngay cả khi độ sáng giảm xuống mức 2.3 nit độ chính xác này vẫn được giữ nguyên.",
            screen: "iPhone 11 sử dụng Chipset Apple A13 Bionic cùng Ram 4GB. Con chip này được đánh giá là tiết kiệm điện và chạy nhanh hơn so với thế hệ A12. Với bộ xử lý 6 nhân 2x2.65 GHz Lightning và CPU thunder 4x1.8 GHz. Neural Engine thế hệ 3 có 8 nhân phụ trách tính năng xử lý hình ảnh như Night Mode và Deep Fusion.\nH3: Hệ điều hành",
        },
        {
            id: 25,
            name: "Samsung Galaxy S22 Ultra (8GB - 128GB)",
            price: 30990000,
            salePrice: 25090000,
            amount: 100,
            type: "samsung",
            image: "https://cdn2.cellphones.com.vn/358x/media/catalog/product/l/a/layer_20.jpg",
            cloudinary_id: "",
            rating: 0,
            os: "android",
            ram: "8GB",
            battery: "5000mAh",
            rom: "256GB",
            camera: "40MP",
            special:
                "Những nâng cấp lớn về hiệu năng, dung lượng pin, và trên hết là camera sau chính là những điểm khiến nó trở thành siêu phẩm trong phân khúc cao cấp. Dưới đây là những thông tin cần biết về dòng điện thoại vừa ra mắt của Samsung. Dưới đây là thông số cấu hình của Samsung S22 Ultra vừa được gã khổng lồ Hàn Quốc giới thiệu.",
            design: "Samsung Galaxy S22 Ultra đi theo ngôn ngữ thiết kế nguyên khối - kính cao cấp và sang trọng, vốn đã làm nên sự thành công của model tiền nhiệm. Chiếc máy có thiết kế mặt lưng đơn sắc tối giản nhưng không kém phần tinh tế, và màn hình tràn viền bao phủ gần như trọn mặt trước, tạo nên trải nghiệm quan sát rộng rãi trên một thiết bị di động nhỏ gọn vừa tay cầm.",
            screen: "Với Galaxy S22 Ultra thì Samsung đã cho ra đời loại màn hình phủ trọn mặt trước đầy ấn tượng. Chiếc màn hình điện thoại có kích thước 6.8 inch, độ phân giải Quad HD+ (3200 x 1440 pixels) và sử dụng tấm nền Dynamic AMOLED 2X với Vision Booster cho ra độ bão hòa màu sắc đầy chân thực.",
        },
        {
            id: 26,
            name: "Xiaomi Redmi Note 11 Pro Plus 5G",
            price: 9990000,
            salePrice: 8890000,
            amount: 100,
            type: "redmi",
            image: "https://cdn2.cellphones.com.vn/358x/media/catalog/product/1/1/11pr-b.jpg",
            cloudinary_id: "",
            rating: 0,
            os: "android",
            ram: "4GB",
            battery: "4000mAh",
            rom: "64GB",
            camera: "60MP",
            special:
                "Đón đầu thử thách, bứt phá mọi tựa game - Chip MediaTek Dimensity 920 5G 8 nhân siêu mạnh mẽ\nKhông gian giải trí đỉnh cao - Màn hình AMOLED 6.67 inch sắc nét, tần số quét 120Hz mượt mà\nSạc nhanh thần tốc, tràn đầy năng lượng - Dung lượng pin lớn 4500mAh, sạc nhanh đến 120W\nTrải nghiệm nhiếp ảnh cực đỉnh - Camera chính 108MP, hỗ trợ nhiều chế độ chụp linh hoạt",
            design: "Điện thoại Redmi Note 11 Pro+ có thiết kế thanh lịch và vuông vắn hơn, mặt trước và sau được vát phẳng hơn mang đến kiểu dáng hiện đại, hợp xu hướng. Bốn góc của smartphone vẫn được bo cong để hài hòa với tổng thể, mềm mại cũng như cầm nắm thoải mái.",
            screen: "Redmi Note 11 Pro Plus chính là mẫu smartphone tầm trung tiếp theo được Xiaomi cho ra mắt với giá hấp dẫn cùng với thiết kế mới tinh tế, cấu hình mạnh mẽ và cụm camera chất lượng cao cho trải nghiệm nhiếp ảnh đầy hứa hẹn.",
        },
        {
            id: 27,
            name: "OPPO Reno6 Z 5G",
            price: 9490000,
            salePrice: 6790000,
            amount: 100,
            type: "oppo",
            image: "https://cellphones.com.vn/mieng-dan-cuong-luc-iphone-11-pro-max-mibow-kingbull-hd-premium.html?itm=related-product",
            cloudinary_id: "",
            rating: 0,
            os: "android",
            ram: "4GB",
            battery: "4500mAh",
            rom: "64GB",
            camera: "50MP",
            special:
                "iếp nối sự thành công của Reno5 Series, Oppo tiếp tục mang đến cho người dùng dòng sản phẩm mới mang tên Oppo Reno6 với nhiều nâng cấp đáng giá. Trong series lần này, người dùng sẽ thấy vô cùng ngạc nhiên khi xuất hiện tới 4 phiên bản. Sự có mặt của Oppo Reno6 Z 5G trong lần ra mắt này sẽ thu hút được đông đảo người chú ý bởi hiệu năng cực đỉnh để mang đến những trải nghiệm đỉnh cao.",
            design: "Điện thoại Reno6 Z 5G sở hữu thiết kế vô cùng thời thượng. Các đường nét, chi tiết trên máy được trau chuốt hoàn hảo và cực kỳ hấp dẫn. Các khung viền bo cong uyển chuyển, mềm mại mang đến cho người dùng cảm giác êm tay khi cầm nắm. Ngoài ra, kích thước tổng thể của máy rất nhỏ gọn và thuận tiện để người dùng mang theo bên mình mọi nơi.",
            screen: "Bên cạnh thiết kế nổi trội thì Reno6 Z 5G còn được trang bị màn hình lớn với tấm nền AMOLED chất lượng. Bên cạnh đó độ phân giải FHD+ mang đến chất lượng hình ảnh vô cùng chân thật và sắc nét.",
        },
        {
            id: 28,
            name: "iPhone 13 Pro Max 128GB | Chính hãng VN/A",
            price: 34990000,
            salePrice: 26990000,
            amount: 100,
            type: "iphone",
            image: "https://cdn2.cellphones.com.vn/358x/media/catalog/product/4/8/4824327_cover_iphone-11-mint211_1.jpg",
            cloudinary_id: "",
            rating: 0,
            os: "ios",
            ram: "16GB",
            battery: "3200mAh",
            rom: "128GB",
            camera: "85MP",
            special:
                "iPhone 13 Pro Max đã khiến bao tín đồ công nghệ ngóng chờ. Cụm camera được nâng cấp, màu sắc mới, đặc biệt là màn hình 120Hz với phần notch được làm nhỏ gọn hơn chính là những điểm làm cho thu hút mọi sự chú ý trong năm nay.",
            design: "Dòng iPhone 12 được Apple áp dụng ngôn ngữ thiết kế tương tự iPhone 12 năm ngoái với phần cạnh viền máy được dát phẳng sang trọng cùng bốn góc được làm bo cong nhẹ, đây có thể được xem là một thiết kế hoài cổ từ dòng iPhone 5 trước đó. Vì thế mà iPhone 13 Pro Max nói riêng, cũng như dòng điện thoại iPhone 13 nói chung, cũng sẽ đi theo ngôn ngữ thiết kế này.\n",
            screen: 'Một trong những yếu tố khiến iPhone 13 Pro Max đáng mong chờ đó là thiết kế notch "tai thỏ" được thu gọn lại. Ngoài kích cỡ màn hình 6.7 inch với tấm nền Super Retina XDR OLED, máy sẽ có thiết kế notch được thu hẹp lại, giúp tăng tỷ lệ hiển thị trên màn hình điện thoại. Tất nhiên, những cảm biến quan trọng như TrueDepth, Face ID hoặc camera selfie đều sẽ giữ nguyên vị trí.',
        },
        {
            id: 29,
            name: "Samsung Galaxy Z Fold3 5G",
            price: 41990000,
            salePrice: 30990000,
            amount: 100,
            type: "samsung",
            image: "https://cdn2.cellphones.com.vn/358x/media/catalog/product/1/1/11_4_32.jpg",
            cloudinary_id: "",
            rating: 0,
            os: "android",
            ram: "16GB",
            battery: "4500mAh",
            rom: "128GB",
            camera: "70MP",
            special:
                "Với sự thành công đáng kinh ngạc và luôn cháy hàng từ lúc ra mắt đến thời điểm hiện tại của hai thế hệ trước là Fold 1 và Z Fold 2. Phiên bản Samsung Galaxy Z Fold3 lần này được ra mắt với độ hoàn thiện cao về thiết kế và hiệu năng. Mang đến cho người dùng một trải nghiệm cực kỳ thú vị hơn.",
            design: "Là sản phẩm mang đến độ hoàn thiện cao hơn nhiều so với hai phiên bản trước, điện thoại màn hình gập mới được thiết kế kích thước hài hòa hơn. Giúp bạn có thể dễ dàng cầm khi đóng hoặc mở màn hình đều dễ sử dụng nhất. Bộ khớp nối bản lề mới giúp kết nối bộ khung của Samsung Fold 3 hoàn hảo hơn. Tăng cao độ bền khi đóng mở liên tục và cố định cực kỳ chắc chắn.",
            screen: "Điểm nổi bật nhất trên chiếc laptop này đó là hệ thống màn hình được trang bị. Cũng giống như thế hệ Fold 2 trước lần này Samsung Fold 3 cũng được trang bị một màn hình chính và một màn hình phụ rất tiện lợi.\n\nĐối với màn hình chính Samsung đã sử dụng loại màn hình Dynamic Amoled công nghệ mới với kích thước chuẩn đạt 7.6 inch. độ phân giải của màn hình này được nâng cấp với chuẩn 2K cực kỳ sắc nét và nổi bật.",
        },
        {
            id: 30,
            name: "Samsung Galaxy A73 (5G) 256GB",
            price: 12990000,
            salePrice: 10690000,
            amount: 100,
            type: "samsung",
            image: "https://cdn2.cellphones.com.vn/358x/media/catalog/product/3/5/35_1_40.jpg",
            cloudinary_id: "",
            rating: 0,
            os: "android",
            ram: "16GB",
            battery: "5000mAh",
            rom: "256GB",
            camera: "32MP",
            special:
                "Điện thoại cao cấp nhất dòng Galaxy A series sở hữu nhiều nâng cấp đáng giá so với thế hệ trước, từ ngoại hình cho đến hiệu năng, đặc biệt là hệ thống camera. Sau đây là những đánh giá chi tiết về chiếc Samsung A73 giúp bạn có cái nhìn tổng quan nhất về chiếc smartphone cận cao cấp này.",
            design: "Trước khi mua bất kỳ chiếc điện thoại nào, người dùng cũng sẽ quan tâm đến thiết kế sản phẩm trước. Với phiên bản A73, Samsung đã tạo nên một chiếc smartphone với vẻ ngoài mang đến cảm giác sang trọng và tinh tế.",
            screen: "Một điểm sáng nổi bật khi nói đến khả năng chụp ảnh của chiếc Samsung A73 là chiếc điện thoại được nhà sản xuất hỗ trợ một hệ thống camera gồm tới 4 bộ cảm biến ở phía sau với chất lượng độ phân giải khác nhau. So với Samsung A72, thiết bị đã lược bỏ ống kinh zoom quang 3x và tele, đồng thời thay thế bằng một cảm biến chiều sâu.",
        },
        {
            id: 31,
            name: "Nubia Red Magic 7 Obsidian 12GB 128GB",
            price: 18990000,
            salePrice: 18490000,
            amount: 100,
            type: "nubia Red Magic",
            image: "https://cdn2.cellphones.com.vn/358x/media/catalog/product/n/u/nubia_red_magic_7_supernova_18gb_256gb.jpg",
            cloudinary_id: "",
            rating: 0,
            os: "android",
            ram: "12GB",
            battery: "6000mAh",
            rom: "128GB",
            camera: "32MP",
            special:
                "Điện thoại Nubia Red Magic 7 có những cải tiến vượt bậc. Đây sẽ là 1 chiếc gaming phone có chip chơi game riêng biệt bên cạnh chip xử lý Snapdragon 8 gen 1. Chiếc smartphone này của nhà ZTE hứa hẹn sẽ mang đến những trải nghiệm chơi game đỉnh cao và mạnh mẽ.",
            design: "Tiếp nối thành công của những phiên bản gaming phone trước đó, sự ra mắt của những chiếc Nubia RedMagic 7 nhận được kỳ vọng cực cao từ thị trường. Đối với 1 chiếc gaming phone tốc độ xử lý là điều được người dùng đặt lên hàng đầu và chiếc điện thoại thế hệ mới của ZTE này đã đánh vào yếu tố đó bằng cách trang bị thêm cho máy chip chơi game riêng biệt bên cạnh chip xử lý snapdragon cực mạnh mẽ.",
            screen: "Nubia Red Magic 7 không sử dụng màn Amoled như thế hệ tiền nhiệm thay vào đó nó sử dụng màn hình OLED với độ tải trọng và phản sáng cực tối ưu. Với việc sử dụng màn hình 6.8 inch 165Hz và có độ phân giải Full HD anh em sẽ có được trải nghiệm chơi game cực đã.",
        },
        {
            id: 32,
            name: "Samsung Galaxy S22 Plus (8GB + 128GB)",
            price: 25990000,
            salePrice: 20190000,
            amount: 100,
            type: "samsung",
            image: "https://cdn2.cellphones.com.vn/358x/media/catalog/product/s/2/s22_2_1.jpg",
            cloudinary_id: "",
            rating: 0,
            os: "android",
            ram: "8GB",
            battery: "3000mAh",
            rom: "128GB",
            camera: "30MP",
            special:
                "Tiếp nối sự thành công của Galaxy S21 Plus thì Samsung lại chuẩn bị ra mắt siêu phẩm mới trong năm 2022, đó chính là Samsung S22 Plus. Đây được coi là một kỳ quan mà người dùng có thể trải nghiệm thiết kế ấn tượng, hiệu năng mạnh mẽ với những công nghệ hàng đầu, cùng với đó là camera vô cùng độc đáo mà bạn chưa từng được chiêm ngưỡng.",
            design: "Galaxy S22 Plus sở hữu thiết kế vô cùng ấn tượng tương tự như trên phiên bản S21 Plus trước đó. Với thiết kế khung viền Armor Aluminum chất lượng cao, mặt kính Corning® Gorilla® Glass Victus®+ từng chi tiết được hoàn thiện một cách tỉ mỉ và tinh tế. Nó mang đến sự mềm mại và vô cùng khéo léo ở mọi góc cạnh, vừa tăng độ sang trọng, vừa bảo vệ máy được an toàn hơn.",
            screen: "Samsung Galaxy S22 Plus được trang bị màn hình tràn viền vô cùng ấn tượng. Kích thước 6.6 inch cùng thiết kế đục lỗ giúp mang đến không gian hiển thị khá rộng để người dùng có thể đắm chìm trong quá trình sử dụng. Chế độ màn hình luôn hiển thị giúp dễ dàng trong việc quan sát giờ, thông báo mà không cần phải đánh thức máy.",
        },
        {
            id: 33,
            name: "OPPO Reno7 Z (5G)",
            price: 10490000,
            salePrice: 9090000,
            amount: 100,
            type: "oppo",
            image: "https://cdn2.cellphones.com.vn/358x/media/catalog/product/7/z/7z_1_1.jpg",
            cloudinary_id: "",
            rating: 0,
            os: "android",
            ram: "8GB",
            battery: "2500mAh",
            rom: "64GB",
            camera: "64MP",
            special:
                "OPPO Reno7 Z chiếc smartphone 5G mới nhất của OPPO thuộc phân khúc tầm trung nhưng chứa đựng cấu hình không thua gì điện thoại phân khúc cao cấp sẽ khuấy động làng công nghệ trong năm 2022.",
            design: 'Điện thoại OPPO Reno 7Z 5G được ra mắt thuộc dòng Reno7 series mới đây của hãng OPPO. Vì thuộc cùng "họ hàng" Reno7, nên máy có ngoại hình khá giống với Reno 7 (bản Trung Quốc) trước đó, với khung viền vuông dát phẳng cùng thân hình vừa tay cầm giúp làm nên chất lượng toàn bộ thân máy. Và chất liệu nguyên khối làm nên khung viền máy cũng góp phần gia tăng độ bền cho sản phẩm.',
            screen: "Điện thoại OPPO Reno7 Z 5G mang đến cho bạn khung ảnh giải trí chất lượng cao với màn hình 6.43 inch công nghệ AMOLED. Màn hình có thiết kế gần như trọn mặt trước cùng nốt chấm ở góc trái màn hình, với vị trí chấm này là nơi hiện diện của camera selfie trên máy. Đáng chú ý là viền bezel và cằm màn hình đã được thu gọn hơn so với mẫu Reno 7 thường, qua đó giúp mở rộng tỷ lệ hiển thị và tạo hình ảnh thêm sống động.",
        },
        {
            id: 34,
            name: "Samsung Galaxy A03s",
            price: 3690000,
            salePrice: 3200000,
            amount: 100,
            type: "samsung",
            image: "https://cdn2.cellphones.com.vn/358x/media/catalog/product/s/a/samsung-galaxy-a03s-600x600_1.jpg",
            cloudinary_id: "",
            rating: 0,
            os: "android",
            ram: "8GB",
            battery: "5000mAh",
            rom: "128GB",
            camera: "13MP",
            special:
                "Với người dùng công nghệ ưa chuộng chiếc smartphone đơn giản, mang vẻ ngoài năng động và hỗ trợ đầy đủ tính năng thiết yếu, Samsung A03s sẽ là sản phẩm điện thoại phù hợp cho nhu cầu ấy.",
            design: "Điện thoại Samsung Galaxy A03s tiếp nối phong cách thiết kế năng động đã làm nên thành công của Galaxy A02s trước đó. Chiếc máy mang kiểu dáng tinh giản, thiết kế thon gọn với nhiều lựa chọn màu sắc phù hợp với sở thích của bạn. Được chế tác với những đường nét mềm mại cùng trọng lượng nhẹ, A03s sẽ luôn đồng hành trên tay bạn trong cuộc sống hiện đại.",
            screen: "Galaxy A03s mang đến cho bạn màn hình hiển thị tràn viền siêu mỏng Infinity-V siêu bắt mắt cho mọi nhu cầu giải trí. Màn hình có kích thước rộng 6.5 inch, có độ phân giải HD+ với mặt kính phủ giúp tăng độ mượt khi vuốt chạm. Tỷ lệ hiển thị 20:9 chuẩn điện ảnh sẽ giúp bạn thỏa thích xem phim trên chiếc smartphone này",
        },
        {
            id: 35,
            name: "Nokia G10",
            price: 3690000,
            salePrice: 2990000,
            amount: 100,
            type: "nokia",
            image: "https://cdn2.cellphones.com.vn/358x/media/catalog/product/t/_/t_i_xu_ng_3__1.png",
            cloudinary_id: "",
            rating: 0,
            os: "android",
            ram: "4GB",
            battery: "3500nAh",
            rom: "64GB",
            camera: "13MP",
            special:
                "Hãng điện thoại lừng danh Nokia vừa qua đã giới thiệu đến giới công nghệ sản phẩm mới mang tên Nokia G10. Đây là chiếc smartphone tập trung vào hiệu năng gaming với vi xử lý MediaTek G22 cùng dung lượng pin 5050mAh chỉ với mức giá rẻ giúp cho nhiều người dễ dàng tiếp cận.",
            design: "Nokia G10 áp dụng ngôn ngữ thiết kế trên các dòng smartphone Nokia, mang đến vẻ ngoài trang nhã & đẹp mắt. Mặt lưng được bo cong giúp người dùng cầm nắm dễ dàng trên tay, với cụm camera sau thiết kế dạng tròn độc đáo.",
            screen: "Nokia G10 được trang bị màn hình kích thước 6.5 inch, độ phân giải HD+ và dùng tấm nền cao cấp có độ sáng cao. Thiết kế viền siêu mỏng ở hai bên chính là yếu tố giúp cho Nookia G10 phù hợp với nhu cầu xem phim, chơi game và giải trí đa phương tiện.",
        },
        {
            id: 36,
            name: "Tecno Pova 2",
            price: 3990000,
            salePrice: 3190000,
            amount: 100,
            type: "tecno",
            image: "https://cdn2.cellphones.com.vn/358x/media/catalog/product/t/e/tecno-pova-2-1.jpg",
            cloudinary_id: "",
            rating: 0,
            os: "android",
            ram: "4GB",
            battery: "7000mAh",
            rom: "32GB",
            camera: "15MP",
            special:
                "Điện thoại Tecno Pova 2 là thương hiệu điện thoại khá xa lạ với người tiêu dùng Việt. Chiếc điện thoại này được nhận xét có chất lượng vượt xa mong đợi ở một thiết bị điện tử phân khúc thấp. Nếu đang tìm kiếm cho mình một chiếc điện thoại đẹp cá tính về hình thức cùng sự hiện đại trong chức năng thì chiếc máy này chắc chắn là đáp án khiến bạn hài lòng",
            design: "Những chiếc điện thoại Pova 2 Tecno có một vẻ đẹp hiện đại lịch lãm như những quý ông khoác lên mình bộ suit mạnh mẽ. Thiết kế hiện đại của chiếc điện thoại này thể hiện ở những đường cắt táo bạo và sắc nét. Mặt lưng được thiết kế khá bóng bẩy với đường sọc dài ở chính giữa, camera được xếp theo cụm nằm ở góc trên bên trái có màu sắc nổi bật so với tổng thể.",
            screen: "Ngay từ khi ra mắt, Pova Tecno 2 đã nhanh chóng gia nhập hội Smartphone màn hình rộng. Chiếc điện thoại này có màn hình 6,9 inch thuộc hàng rộng nhất nhì thị trường điện thoại. Với khung chắc chắn, viền siêu mỏng, chiếc điện thoại này sẽ trình diễn trước mắt bạn khung hình hiển thị rộng bậc nhất giới smartphone.",
        },
        {
            id: 37,
            name: "Tecno Spark 7T 4GB 64GB",
            price: 3090000,
            salePrice: 2650000,
            amount: 100,
            type: "tecno",
            image: "https://cdn2.cellphones.com.vn/358x/media/catalog/product/t/e/tecno-spark-7t-1.png",
            cloudinary_id: "",
            rating: 0,
            os: "android",
            ram: "15GB",
            battery: "6500mAh",
            rom: "64GB",
            camera: "32MP",
            special:
                "Tecno Spark 7T là chiếc smartphone giá rẻ được rất nhiều khách hàng săn đón trên thị trường. Điện thoại không chỉ ấn tượng nhờ thiết kế trẻ trung, bắt mắt mà chúng còn thu hút người dùng nhờ dung lượng pin siêu khủng, siêu ấn tượng. Với những gì trang bị chắc chắn chúng sẽ mang tới cho người dùng trải nghiệm vô cùng bất tận.",
            design: "Điện thoại Tecno Spark 7T được khoác lên mình vẻ ngoài vô cùng thời trang và tinh tế. Cụm camera được trau chuốt vô cùng tỉ mỉ giúp tạo điểm nhấn cho mặt lưng. Đặc biệt hơn nữa, ở mặt lưng của máy logo SPARK vô cùng nổi bật và được bao quanh bởi những đường vân chéo. Từ đó tạo nên sự độc đáo cũng như cảm giác cầm nắm vô cùng chắc chắn.",
            screen: "Là chiếc điện thoại thuộc phân khúc giá rẻ, tuy nhiên điện thoại di động Tecno Spark 7T lại được trang bị bộ vi xử lý Helio G35 khá ấn tượng. Với tiến trình sản xuất 8 nhân mang tới khả năng hoạt động mượt mà ngay khi video trực tuyến, truy cập vào mạng xã hội hay là chơi game,…",
        },
        {
            id: 38,
            name: "Xiaomi 12 Pro (5G)",
            price: 27990000,
            salePrice: 21990000,
            amount: 100,
            type: "xiaomi",
            image: "https://cdn2.cellphones.com.vn/358x/media/catalog/product/t/_/t_i_xu_ng_2__3_2.png",
            cloudinary_id: "",
            rating: 0,
            os: "android",
            ram: "13GB",
            battery: "3000mAh",
            rom: "64GB",
            camera: "20MP",
            special:
                "Là một trong những dòng smartphone chủ lực của hãng, Xiaomi 12 Pro sở hữu một thiết kế ấn tượng cùng hiệu năng vượt trội mang lại trải nghiệm dùng mượt mà. Bên cạnh đó, máy còn được trang bị hệ thống camera vô cùng chất lượng cho ra những bức ảnh chuyên nghiệp.",
            design: "Điện thoại Xiaomi 12 Pro 5G sở hữu một thiết kế hoàn toàn khác biệt so với Xiaomi Mi 11 trước đó. Đường nét tinh tế, mượt mà, cầm mượt mịn trên tay, mặt sau là cụm camera được sắp xếp lại, mang lại điểm nhấn riêng.\n",
            screen: "Điện thoại Xiaomi 12 Pro được trang bị màn hình AMOLED với khung viền siêu mỏng, kích thước 6.73 inch mang lại tỉ lệ hiển thị lớn. Màn hình AMOLED DotDisplay được hoàn thiện cùng công nghệ AdaptiveSyncPro rõ nét, mượt mà và đỉnh cao. Độ phân giải màn hình lên đến 3200x1440, mật độ điểm ảnh 522 PPI. Nhờ vậy mà có thể đáp ứng tiêu chuẩn khắt khe về hình ảnh. ",
        },
        {
            id: 39,
            name: "Xiaomi Mi 11 5G",
            price: 21990000,
            salePrice: 15200000,
            amount: 100,
            type: "xiaomi",
            image: "https://cdn2.cellphones.com.vn/358x/media/catalog/product/x/i/xiaomi-mi11-1.jpg",
            cloudinary_id: "",
            rating: 0,
            os: "android",
            ram: "8GB",
            battery: "4600mAh",
            rom: "64GB",
            camera: "108MP",
            special:
                "Một trong những chiếc smartphone được các Mi Fan mong chờ nhất năm nay đó chính là Xiaomi Mi 11. Trang bị vi xử lý Snapdragon 888 hỗ trợ 5G với thiết kế màn hình tràn viền ấn tượng, đây sẽ là chiếc flagship nổi bật của Xiaomi trong năm nay. Ngoài ra, bạn cũng có thể tham khảo thêm điện thoại Mi 11 Lite khả năng cao sẽ được bán tại CellphoneS trong thời gian gần nhất.",
            design: "Tính sang trọng chuẩn flagship của Mi 11 được thể hiện đầu tiên qua thiết kế vuông vức bốn góc cạnh đầy lịch lãm. Máy còn có độ cứng cáp nhờ chất liệu kim loại sang trọng cùng kính cường lực phủ đều hai mặt trước & sau. Độ mỏng ấn tượng cũng là một điểm đáng chú ý trên thiết kế thân máy.",
            screen: "Điện thoại Xiaomi Mi 11 gây chú ý với cụm camera 3 ống kính ở mặt sau. Trong đó, ống kính có độ phân giải lớn nhất là camera chính 108 MP sẽ mang đến cho người dùng bức ảnh rõ & sắc nét nhất. Hai camera còn lại bao gồm ống kính 13MP góc rộng và camera 5MP.\n",
        },
        {
            id: 40,
            name: "Realme C35 4GB 64GB",
            price: 4290000,
            salePrice: 3790000,
            amount: 100,
            type: "realme",
            image: "https://cdn2.cellphones.com.vn/358x/media/catalog/product/f/r/frame3934-640x640.png",
            cloudinary_id: "",
            rating: 0,
            os: "android",
            ram: "8GB",
            battery: "3000mAh",
            rom: "32GB",
            camera: "50MP",
            special:
                "Dòng sản phẩm mới nhất Realme C35 vừa được hãng chuẩn bị tung ra thị trường. Tuy thuộc phân khúc giá rẻ nhưng C35 vẫn được trang bị rất nhiều tính năng hiện đại và cao cấp từ thiết kế tới hiệu năng. Chắc chắn đây sẽ là chiếc smartphone phù hợp với mọi đối tượng khách hàng hiện nay.",
            design: "Điện thoại Realme C35 được thiết kế màn hình kiểu “giọt nước” thời thượng bắt kịp xu hướng cùng với kích thước lên đến 6.6 inch mang đến khả năng hiển thị nội dung được đầy đủ hơn. Người dùng thoải mái trải nghiệm giải trí, xem video hay đọc tin tức trên điện thoại.",
            screen: "Điện thoại Realme C35 sở hữu hiệu năng mạnh mẽ nhờ trang bị bộ vi xử lý Unisoc T616 8 nhân với xung nhịp 2 nhân là 1.95GHz cùng với đó là 6 nhân còn lại sẽ có xung nhịp 1.82GHz. GPU Mali-G57 kết hợp cùng mang tới khả năng hoạt động mạnh mẽ. Người dùng có thể thoải mái sử dụng để lướt web, xem phim hay chơi game mà không lo giật lag.",
        },
        {
            id: 41,
            name: "Realme C21Y",
            price: 3690000,
            salePrice: 3690000,
            amount: 100,
            type: "realme",
            image: "https://cdn2.cellphones.com.vn/358x/media/catalog/product/r/e/realme-c21y-1.jpg",
            cloudinary_id: "",
            rating: 0,
            os: "android",
            ram: "15GB",
            battery: "5000mAh",
            rom: "64GB",
            camera: "13MP",
            special:
                "Sở hữu dung lượng pin cực khủng cùng màn hình giọt sương với kích thước lớn, đây là chiếc điện thoại thông minh hứa hẹn mang đến cho người dùng những trải nghiệm mượt mà, lướt web và tha hồ chơi game.",
            design: "Realme C21Y vẫn giữ nguyên vẻ thiết kế bên ngoài như thế hệ tiền nhiệm của chúng. Máy được thiết kế nguyên khối với lưng và khung viền hoàn thiện từ chất liệu nhựa. Chúng vừa đảm bảo được độ chắc chắn, nhẹ nhàng và tiết kiệm được tối đa giá thành.",
            screen: "Điện thoại Realme C21Y được trang bị màn hình khá rộng cùng thiết kế giọt nước. Thiết kế này mang đến khả năng hiển thị rộng hơn, lớn hơn để người dùng đắm chìm trong mọi trải nghiệm.\n",
        },
        {
            id: 42,
            name: "OPPO Reno7 4G (8GB - 128GB)",
            price: 8990000,
            salePrice: 7590000,
            amount: 100,
            type: "oppo",
            image: "https://cdn2.cellphones.com.vn/358x/media/catalog/product/t/_/t_i_xu_ng_17__1_3.png",
            cloudinary_id: "",
            rating: 0,
            os: "android",
            ram: "5GB",
            battery: "5000mAh",
            rom: "32GB",
            camera: "64MP",
            special:
                "Oppo Reno 7 4G sở hữu camera trước với cảm biến IMX709, đây là cảm biến độc quyền được xây dựng bằng phần cứng của Sony với khả năng thu sáng cao nhờ đó mang lại chất lượng hình ảnh với độ sáng cao. Bên cạnh đó là cảm biến RGBW giúp thu sáng nhiều hơn tới 60%.",
            design: "Về thiết kế, Oppo Reno 7 4G sở hữu bốn viền được vát phẳng sang trong cùng các góc bo cong nhẹ mang lại trải nghiệm cầm nắm vô cùng thoải mái. Điện thoại với hai phiên bản màu trong đó phiên bản 4G vàng với thiết kế da sợi thủy tinh giúp mặt lưng nhẹ hơn, sang trọng hơn. Chất liệu da sợi này vô cùng bền bỉ khi vượt qua bài kiểm tra 200000 lần ma sát.",
            screen: "Oppo Reno 7 4G được trang bị màn hình thiết kế đục lỗ với kích thước lên đến 6,4 inch. Kết hợp với viền màn hình siêu mỏng giúp máy có không gian hiển thị rộng lớn. Màn hình được trang bị tần số quét 90Hz giúp các chuyển động chạm vuốt diễn ra mượt mà và ổn định.",
        },
        {
            id: 43,
            name: "iPhone 12 64GB I Chính hãng VN/A",
            price: 22990000,
            salePrice: 15990000,
            amount: 100,
            type: "iphone",
            image: "https://cdn2.cellphones.com.vn/358x/media/catalog/product/1/2/121775005_214053020136993_4215871422753310748_n_1.jpg",
            cloudinary_id: "",
            rating: 0,
            os: "ios",
            ram: "16GB",
            battery: "3200mAh",
            rom: "64GB",
            camera: "32MP",
            special:
                'iPhone 12 vẫn đang là một trong những sự lựa chọn hàng đầu ở thời điểm hiện tại. Chiếc flagship năm 2020 của "Táo khuyết" đang nhận được rất nhiều sự quan tâm của người dùng bởi mức giá dễ tiếp cận hơn so với thời điểm ra mắt, đồng thời được trang bị cấu hình, màn hình, camera ấn tượng trong tầm giá.',
            design: "iPhone 12 gây ấn tượng với người dùng bởi thiết kế vuông vức quen thuộc, đây là thiết kế đã từng xuất hiện trên thế hệ iPhone 5 trước đó. Điện thoại được hoàn thiện mỏng hơn với cụm camera lớn hơn.\n\nĐặc biệt, máy được trang bị một khung viền thép không gỉ. Mặt lưng điện thoại iPhone 12 được trang bị một mặt kính Ceramic Shield bóng bẩy, gây được sự chú ý của người đối diện.",
            screen: "Màn hình là một điểm nhấn trên iPhone 12. Máy được trang bị tấm nền Super Retina XDR OLED, thay vì IPS LCD như thế hệ trước đó nhờ vậy người dùng sẽ cảm nhận được khả năng hiển thị sinh động, màu sắc đậm đà cũng như độ tương phản cao.",
        },
    ],
};
